spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kele
    password: kele
    url: jdbc:mysql://localhost:3306/mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

debug: true
logging:
  level:
    com.aikele: debug
